services:
  db:
    image: mysql:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot1!
      MYSQL_DATABASE: erla
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
